### PR TITLE
Update modDesc_l10n_ru.xml

### PR DESCRIPTION
**Pull request by Gonimy-Vetrom**
Please add these lines (128, 129) to your gearboxMogli.lua file so that I can translate. :) 
Everything else I already translated. Now I'm doing it checking.

### CODE REVIEW

**Comment by Gonimy-Vetrom** [comment]
Also need 
line 5099: "Cannot shift gear clutch > %3.0f%%"
line 5113: "Cannot shift gear speed > %3.0fkm/h"

Thanks for the mod.

**Comment by Mogli12** [comment]
Ok, please check v3.0 build 210

**Comment by Gonimy-Vetrom** [comment]
Thank you. Working! 
Can you add two more lines?
line 3518: "Speed Limiter: +%2.0f km/h/s / -%2.0f km/h/s"
and
line 3522: "Speed Limiter: +%2.0f km/h/s / -%2.0f km/h/s"

**Comment by Gonimy-Vetrom** [comment]
In file gearboxMogliMotor.lua there are such lines:
line 3904: "Motor stopped because RPM too low: %4.0f < %4.0f"
line 3905: "RPM is too low: %4.0f < %4.0f"
line 3907: "RPM is too low: %4.0f < %4.0f"
line 3997: "Clutch is overheating"

Can you also put them in a file for translation?

Thank you!!!

**Comment by Gonimy-Vetrom** [comment]
fsscreen_2017_10_21_17_46_23

**Comment by Mogli12** [comment]
Good point!

**Comment by Gonimy-Vetrom** [comment]
Thanks for the update.
I have a difficulty with translating this phrase: "swap gears"
in line <text name="gearboxMogliTEXT_SwapGearRangeKeys"  text="swap gears and range 1"/>
Does the word "swap" have synonyms? Or is this one phrase meaning mechanism?
I can not even find it in the old paper dictionary. :)

**Comment by Mogli12** [comment]
swap or exchange. You have controls for gears and for ranges. With the setting you exchange the controls, so the controls for gears change ranges and the controls for ranges change gears.

**Comment by Gonimy-Vetrom** [comment]
Thank you! This explanation needs to be added to the Wiki.

**Comment by Mogli12** [comment]
The wiki is really very incomplete. But I am not so happy with the wiki framework of github.

**Comment by Gonimy-Vetrom** [comment]
fsscreen_2017_10_29_19_30_05

**Comment by Gonimy-Vetrom** [comment]
I need one more line for translation: gearboxMogli.lua line: 4733

<text name="gearboxMogliUNIT_tph"                  text="???/???"/>.

**Comment by Gonimy-Vetrom** [comment]
fsscreen_2017_10_31_23_46_05

**Pull request merged**
